name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # or [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"] # you can add more python version
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install
        run: pip install -e .[dev,test]
      - name: Run isort
        run: isort myproject --check-only
      - name: Run black
        run: black --check myproject
      - name: Test with pytest
        run: python -m pytest
